// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjhmvlctgxwsvkjelpdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaG12bGN0Z3h3c3ZramVscGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjg0ODgsImV4cCI6MjA2MjIwNDQ4OH0.Wj3b7rZjI0JPMhhV-NlXSihFdhFtqRQ245CCcwF0pwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);